version: '3'
services:

  llm-work: 
    container_name: ${COMPOSE_PROJECT_NAME}-langchain
    build:
      context: ./containers/langchain
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./llm-work:/root/work
